name: goblfc/tracker
services:
  app:
    image: ghcr.io/goblfc/tracker
    build:
      context: ./
      dockerfile: .docker/app/Dockerfile
    restart: always
    env_file:
      - .docker/app.env
    volumes:
      - app-logs:/var/www/html/storage/logs
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    restart: always
    env_file:
      - .docker/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    command:
      - /bin/sh
      - -c
      - redis-server --save 60 1 --loglevel warning --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD not provided}"
    restart: always
    env_file:
      - .docker/redis.env
    volumes:
      - redis:/data

  nginx:
    image: ghcr.io/goblfc/tracker-nginx
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    restart: always
    env_file:
      - .docker/nginx.env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: ghcr.io/goblfc/tracker-certbot
    build:
      context: ./
      dockerfile: .docker/certbot/Dockerfile
    restart: unless-stopped
    env_file:
      - .docker/certbot.env
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx

volumes:
  app-logs:
  postgres:
  redis:
  certbot-conf:
  certbot-www:
