name: GoBLFC/Tracker
services:
  app:
    image: ghcr.io/GoBLFC/Tracker
    build:
      context: ./
      dockerfile: .docker/Dockerfile-app
    restart: always
    env_file:
      - .docker/env/app.env
    volumes:
      - app-logs:/var/www/html/storage/logs
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    restart: always
    env_file:
      - .docker/env/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    command:
      - /bin/sh
      - -c
      - redis-server --save 60 1 --loglevel warning --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD not provided}"
    restart: always
    env_file:
      - .docker/env/redis.env
    volumes:
      - redis:/data

  nginx:
    image: ghcr.io/GoBLFC/Tracker-nginx
    build:
      context: ./
      dockerfile: .docker/Dockerfile-nginx
    restart: always
    env_file:
      - .docker/env/nginx.env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    env_file:
      - .docker/env/certbot.env
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - .docker/certbot-runner.sh:/usr/local/bin/certbot-runner
    entrypoint: /bin/sh /usr/local/bin/certbot-runner
    depends_on:
      - nginx

volumes:
  app-logs:
  postgres:
  redis:
  certbot-conf:
  certbot-www:
