---
name: Publish Images
on:
  push:
    branches:
      - main

permissions:
  packages: write

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - app
          - nginx
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/Dockerfile-${{ matrix.image }}
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: "${{ env.IMAGE_NAME }}-${{ matrix.image }}:${{ steps.checkout.outputs.commit }},${{ env.IMAGE_NAME }}-${{ matrix.image }}:latest"
