---
name: Publish images
on:
  push:
    branches:
      - main

permissions:
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    name: Publish images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: ${{ github.repository }}
            file: .docker/app/Dockerfile
          - name: ${{ github.repository }}-nginx
            file: .docker/nginx/Dockerfile
          - name: ${{ github.repository }}-certbot
            file: .docker/certbot/Dockerfile
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image.name }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build & push container images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image.file }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
